### ISSUE TITLE
Cannot load css module files

### ISSUE THREAD

**Issue by ferretwithaberet** [keycloakify/keycloakify#150]
I imported a css module file like so:

```js
import styles from "./style.module.css";
```

this is how I use the imported styles in case it is relevant but I doubt it is:

```js
    <Component
      className={cx({ // cx is an alias for the "classnames" package
        [styles["email-input-success"]]: valid,
      })}
      // Other props
    >
      {/* Children */}
    </Component>
```

and I got these errors:
![image](https://user-images.githubusercontent.com/46427158/183664020-109f77cf-9852-4e34-9479-fd5974c57f23.png)

this is the content of the css module file:
```css
.email-input-success input {
  @apply !border-green-500 !shadow-none; /* I am using tailwindcss */
}
```

I do not know anything else, I provided all the information I considered relevant. Feel free to ask for more information if you have a clue on why this is happening!

**Comment by garronej** [comment]
@ferretwithaberet This is high in my TODO list.

**Comment by willwill96** [comment]
I am currently using css modules within my keycloakify app with no problems.
What is described in the issue above I think is a limitation of CRA not being able to use custom postcss configs (necessary in order to use `@apply`). [Ref](https://tailwindcss.com/docs/guides/create-react-app), which also a feature I would like to see 😄

**Comment by garronej** [comment]
Fantastic thanks!
