### ISSUE TITLE
Languages and icon

### ISSUE THREAD

**Issue by LeonardaH** [keycloakify/keycloakify#352]
Hey, I am struggling removing and adding new language to language dropdown. Is it possible to customize it? Also is it possible to add an icon as a background image for social provides?

**Comment by garronej** [comment]
Sure hold on

**Comment by garronej** [comment]
Hi @LeonardaH,  

Thaks for reaching out, of course with Keycloakify you can customize literally everything, the only question is what is the best way to do it.  

The language that you see in the dropdown are conditioned by the `kcContext` global. This object contains the keycloak configuration passed over from the Keycloak to your theme.  

So to control what language appears in the dropdown you have two way. One is to go to the Keycloak admin, in real setings -> localization -> and there you can select the language you want to support.   

The other is to to hard code in the theme configuration the languages that you support using the [`extraThemeProperty`](https://docs.keycloakify.dev/build-options#keycloakify.extrathemeproperties) option.  

Regarding having a background image as button for social provider sure it's possible.  
We've done it for [this website](https://sill.code.gouv.fr) for example:  

<img width="1330" alt="image" src="https://github.com/keycloakify/keycloakify/assets/6702424/6f37348a-4f77-41fa-9127-5c62d9e6c238">


The code for this is here:  

https://github.com/codegouvfr/sill-web/blob/893e93e5df281b1d295ce928ca27bc3e0536b516/src/keycloak-theme/login/pages/Login.tsx#L122-L144  

You see, if there is a social provider enabled for wich the display name contains `agentconnect` we use our custom component for AgentConnect.  

I hope it helps  

Best

**Comment by LeonardaH** [comment]
Thanks, it helped me a lot!

**Comment by garronej** [comment]
I'm happy it did, closing now. Feel free to reopen if you have any aditional questions

**Comment by LeonardaH** [comment]
I already asked a question about icons and languaes. Still struggling about some topics in keycloak so I would like to make it clear. Is it possible to edit extra pages like session and application pages? I used command: npx -p keycloakify download-builtin-keycloak-theme to access all the pages that are supported within keycloak. I only can see all the pages as a ftl.files. My question is how to edit and design it for my needs?

**Comment by garronej** [comment]
> pages like session and application pages  

Can you be more specific? What precisely are the pages you are refering to (name of .ftl file and/or screenshot)

**Comment by garronej** [comment]
Ok, I don't provide a builtin React port of this pages but you can customize them anyway!  

If you want to make a contribution to the project you can submit a pull request adding support for this pages as described here: https://docs.keycloakify.dev/contributing#adding-support-for-a-new-page    

Otherwise check the "I do it only for my project" tab of this documentation section: https://docs.keycloakify.dev/limitations#i-have-established-that-a-page-that-i-need-isnt-supported-out-of-the-box-by-keycloakify-now-what  

In your case `my-extra-page-1.ftl` would be `applications.ftl` and `my-extra-page-2.ftl` woult be `sessions.ftl`.  

You would need to list them in the `package.json` here: https://github.com/keycloakify/keycloakify-starter/blob/8b5572414395d012e67f2ee8966123551db2390e/package.json#L25-L28

**Comment by LeonardaH** [comment]
Get it, thank you for your help!

**Comment by garronej** [comment]
@LeonardaH, just so you know, you can now remove `extraAccountPages` from your package.json
