### ISSUE TITLE
Remove unused files from bundled jar

### ISSUE THREAD

**Issue by rogeraugusto** [keycloakify/keycloakify#367]
I´m creating a standalone keycloak login page from `keycloakify-starter` repo and I removed all unecessary files.

![image](https://github.com/keycloakify/keycloakify/assets/18172346/60cbce73-af4f-4356-b734-95b93ecf8979)

But after `yarn build-keycloak-theme`, into jar files, it has all login ftl files.
Is there a config to prevent these additional files being generated and avoid increase bundle size?

![image](https://github.com/keycloakify/keycloakify/assets/18172346/820bbc02-f9fb-45bd-a535-cef617001225)

Another question:
As commented [here](https://github.com/keycloakify/keycloakify/issues/104#issuecomment-1122305399), a big app with only 16mb. Why my this simple jar creates a  ~35 mb file?

**Comment by garronej** [comment]
Hello @rogeraugusto,

> But after yarn build-keycloak-theme, into jar files, it has all login ftl files.

You're inquiring about the possibility of a configuration to prevent additional .ftl files from being generated, thus circumventing an increase in the bundle size.

Indeed, you must keep all those .ftl files. Otherwise, your theme will not function as expected, you will revert to the default Keycloak theme for pages you haven't explicitely ejected.

From what I can gather, you've only customised the Login page so far. However, I suspect you've also made alterations to the logo and background in the Template. Ideally, you'd want these changes to be visible on every page, including the register and info pages, not just the Login page.

> As commented https://github.com/keycloakify/keycloakify/issues/104#issuecomment-1122305399, a big app with only 16mb. Why my this simple jar creates a ~35 mb file?

The reason for the larger size is to future-proof your theme. This approach ensures that your theme remains operational even after a Keycloak server update. Keycloakify encapsulates all the common resources available in a specific version of Keycloak, these resources vary depending on the Keycloak version.

I acknowledge that if you're creating a theme entirely from scratch and not utilising Keycloak's built-in assets, these resources could be considered extraneous. A vast node_modules within Keycloak's shared resources contains numerous elements that are not used even by the default Keycloak theme.

However, my primary focus has been to ensure that what gets shipped to the user's browser is as compact and as lazily loaded as possible. Personally, I don't see an immediate benefit in investing time to reduce the theme bundle size when it doesn't impact the theme performance. However, perhaps there is a use case I'm overlooking that might justify such an effort.

I'd love to hear your thoughts on this.

**Comment by rogeraugusto** [comment]
Firstly, thank you for the clear and detailed answer.

Initially I thought maybe I was missing something in the configuration and found strange generate that files.

But size really isn't an issue at the moment. The project works well and fast, but it always tends to grow as we add new libs and resources.

Anyway, I get the point and thanks for the great job on the project.

Best regards @garronej.

**Comment by garronej** [comment]
@rogeraugusto  In v8 the .jar is not 10 times smaller 🥳

**Comment by rogeraugusto** [comment]
@garronej Awesome! What a greate feature. I'm going to bump here to test. Thanks for nice work!
