### ISSUE TITLE
What if Keycloak instance is down ? 

### ISSUE THREAD

**Issue by PietroFalcetti** [keycloakify/keycloakify#383]
Hello,

Running the starter project as an app in local development, If the keycloak instance the app is trying to connect is not running, the app stays in white screen for about 5 seconds and then shows an error about the jwt_decode unable to parse the token (this is right because the token isn't actually there).
The problem i found is that if i print the oidcClient in the App.tsx component, after the white screen it shows the property isUserLoggedIn with value true, but this should be false by default because the keycloak instance is down.

Anyone has experienced this issue ? Any idea on how to solve ? 

Thank you.

**Comment by garronej** [comment]
Hello @PietroFalcetti,  

I didn't accomodate for the Keycloak server to be down in the example code I give in the starter project.  

Keep in mind that the part related to managing autentication with Keycloak in a React app is out of scope for this project.  
Keycloakify is about generating themes.  
I figured, however that it would be nice to have very simple end-to-end example this is why I provided the `src/App` directory and https://github.com/keycloakify/keycloakify-starter/blob/main/src/App/oidc.tsx.  
If this code dosen't fit your need feel free to change it so it returns `isUserLoggedIn: false` when keycloak is down.  

I wont make this example any more sophisticated because I want the example code to remain readable and to the point.  

Best regards
