### ISSUE TITLE
KcContext: usernameEditDisabled has been renamed to usernameHidden

### ISSUE THREAD

**Issue by DevRebs** [keycloakify/keycloakify#397]
Hello, first off, thanks a lot for your awesome work !

I'd like to report the following issue :
The `usernameEditDisabled` property has been renamed to `usernameHidden` a few months ago and the general display conditions for the username field have changed as a result in the base `login.ftl` template.
Source : https://github.com/keycloak/keycloak/commit/d9c8cb30a5ec2f4a9589cdbfe50bf8c35d9853ad#diff-211584f3e252b06de72bea35ec29af7e7c7236d4094d25eb121f62c1cd41b4f8

Could you please look into it ?

**Comment by garronej** [comment]
Hello @DevRebs,

Thank you for your kind words and for bringing this to our attention.

With Keycloakify, you can be assured that the `kcContext` you receive is always up-to-date. It encompasses everything that's available through the `.ftl` context provided by Keycloak.

However, there's a distinction to be made regarding the type definitions of the `KcContext`. While the actual `kcContext` remains current, its type definitions might not always reflect the latest changes. This is because we hard code these definitions in a "best effort" manner.

Given this context, what would you suggest? Should we update the [type definition](https://github.com/keycloakify/keycloakify/blob/main/src/login/kcContext/KcContext.ts)?

**Comment by DevRebs** [comment]
Hello,

Thank you for the swift answer.

Given this context, I guess that updating the type definition would be welcome, yes. 
 
Please note that, as a result of the change to `usernameEditDisabled`, the `username` field is no longer set to `disabled` but simply left unrendered (see [login.ftl](https://github.com/keycloak/keycloak/blob/main/themes/src/main/resources/theme/base/login/login.ftl) - same logic applies in [login-username.ftl](https://github.com/keycloak/keycloak/blob/main/themes/src/main/resources/theme/base/login/login-username.ftl)). I feel this should be reflected in [Login.tsx](https://github.com/keycloakify/keycloakify/blob/main/src/login/pages/Login.tsx), what do you think ?

**Comment by garronej** [comment]
Hello @DevRebs,  

Yes, I agree!  
Would you submit a PR?

**Comment by DevRebs** [comment]
Hello @garronej ,

I am ready to submit a PR, yes.

**Comment by garronej** [comment]
Great thanks,  

You can always open a PR from a fork!  

However I'll give you the access to push from your branch to save some time

**Comment by garronej** [comment]
Just so you know:  

<img width="1191" alt="image" src="https://github.com/keycloakify/keycloakify/assets/6702424/8174b5b9-b351-4793-ae2d-bce6ebedff12">
You have you click compare across forks
