### ISSUE TITLE
Custom src path

### ISSUE THREAD

**Issue by madroneropaulo** [keycloakify/keycloakify#449]
Hi team!

I'm trying to upgrade my keycloakify app to v8, but the restriction of having the theme source files under the root folder makes it impossible for me since my keycloakify app is inside a monorepo (nx), and the keycloakify command is executed not from the app root, but from the monorepo root, and thus it doesn't find the src/ or src/keycloak-theme or src/keycloak_theme required directories. Is there any deep reason why it's hardcoded to the current working directory root?

**Comment by garronej** [comment]
Hi @madroneropaulo,  

No perticular reason other than trying to keep api surface small.  
Every new params increace the maintenance cost and complexity of the project.  

`cd path/to/your/theme/project && npx keycloakify` maybe?

**Comment by madroneropaulo** [comment]
@garronej thanks for replying! unfortunately that doesn't work, it looks for a package.json (which NX integrated monorepos don't use). And when I provided one, anyway it throws an error that it's looking for the build folder `ENOENT: no such file or directory ........build_keycloak/pom.xml`

**Comment by garronej** [comment]
Oh, I see.  
There has been a couple issues related to monorepos, I've done some stuff about it and pepole seems to got it working somehow.  
Maybe you can have a look at this an telle me what you thiink of it: https://github.com/keycloakify/keycloakify/issues/380  
Is this something that was working only in v7 but no longer in v8?  

There is also this workaround but it's clearly a hack.  
https://github.com/keycloakify/keycloakify/issues/405#issuecomment-1695502386  

If you can describe a desired solution I could implement it.  
I would by far prefer a solution that would involve some inferring instead of a one that would introduce a new param.

**Comment by madroneropaulo** [comment]
I'm in version 6 and trying to upgrade to 8, but I guess this is a v7 introduced problem. Regarding a desired solution, well, I think the best option would be to divide the process in two steps, and let the user configure each, this because many times projects would prefer to reuse code from their core projects (assets, styles, build scripts, etc) to make their keycloak theme look the same. So the first step would be building, the user would choose where and how to build the codebase, and the next step is using that build to generate the keycloak theme, again, the user would have the option to configure where to look for the build. It can default to whatever, but I do think it should be configurable for the same reason.

**Comment by garronej** [comment]
There isn't two step.  
Keycloakify takes as input a build directory generated by Webpack (in the future it will also work with a dist dir generated by Vite) and generate a Keycloak therme. That's it.  
The only thing that have been changed in recent version of Keycloakify is that Keycloakify analyze your source to make some inference about what extra pages your might have defined or what assets from the default theme you are using, this enables to remove a lot of config a just get thing to work out of the box.  

So to enable Keycloakify to work it needs to know where the sources are (See [acceptable source directory structure](https://docs.keycloakify.dev/migration-guides/v6-greater-than-v7)) and where the build dir is.  

Currently Keycloakify assumes thoses two directories are $CWD/src and $CWD/build but I could implement smarter inference or even introduce new buid option.  

If you could provide me with a minimal monorepo setup I can work on this.

**Comment by garronej** [comment]
I'll adress this for good in the v10 (the ones that will bring Vite support)

**Comment by garronej** [comment]
The `-p` or `--project` CLI option should solve this, it will be featured in 9.4.  

`npx keycloakify -p ./web` for examples.

**Comment by garronej** [comment]
Hello @madroneropaulo,  

There is now a section dedicated to monorepo integration in the documentation website.  
https://docs.keycloakify.dev/keycloakify-in-my-app/as-a-subproject-of-your-monorepo  

Let me know if you think it could be improved. For ne Nx integration it's a bit naïve since I don't know how to configure the cache.

**Comment by madroneropaulo** [comment]
Hey @garronej looks good! I have time now to try this and migrate from v8 into our monorepo, I'll let you know. Thanks!
