### ISSUE TITLE
Is it possible to differentiate between "user not found" and "invalid credentials"?

### ISSUE THREAD

**Issue by gilamarko** [keycloakify/keycloakify#455]
When constructing the login-form-error-container, I'm wondering if it is possible to somehow to differentiate between "user not found" and "invalid credentials" and show a custom error message.

**Comment by garronej** [comment]
Hi @gilamarko,  

Maybe `console.log(kcContext)`, see what's inside and if ther's the information you need.

**Comment by gilamarko** [comment]
Hello, thanks for the quick response.

I examined the log of the kcContext as you suggested but the information in the does not differentiate between "user not found" and "invalid credentials". To be more specific the system right now uses the message object inside the kcContext which uses the same summary in both cases. Is there any other suggestion or solution for achieving that? Or it cannon be handled right now?

**Comment by garronej** [comment]
Ok, now that I actually read your title I can confidentyl said that this would be a vulnerability if it was possible.  
This would mean that anyone could check if a given email is registered to your system.  
You can ask chatgpt4 but I Keycloak do not allow this, by design.

**Comment by lordvlad** [comment]
Im pretty certain this is by design. Generally you should not tell anyone
if an account exists or not. Otherwise you allow for username enumeration.
https://www.virtuesecurity.com/kb/username-enumeration/#:~:text=Username%20enumeration%20is%20a%20common,username%20is%20invalid%E2%80%9D%20is%20returned
.

If you really want to make it happen since you operate in a closed
environment you'll need to customize authorization flows and possibly
create a custom spi. Better ask in keycloak community
https://www.keycloak.org/community

**Comment by gilamarko** [comment]
Yes for sure I get your point, I have just integrated a message broker on my API in which I listen to LOGGIN_ERRORS and based on the error I do actions (create users or other staff). So I was wondering if it was possible to show different messaged on our client theme so our User can have a clue about our actions. 

Thanks again for the response.
