### ISSUE TITLE
Function works twice.

### ISSUE THREAD

**Issue by wS2Zth** [keycloakify/keycloakify#483]
Hi there. I am using keycloakify-starter repo. I have added "console.log('LOGINFTL')" to "Login.tsx", this is the only thing I have changed. After that I have use "yarn build-keycloak-theme" and "./build_keycloak/start_keycloak_testing_container.sh" commands respectively. After changing theme when I go to login page console.log('LOGINFTL') -> that method works twice. I am not familiar too much with React but If I do not remember wrong, funcs work twice only in dev mode. Is it normal or I have skipped any step?

**Comment by garronej** [comment]
Hello @wS2Zth,  

You're correct in assessing that the Login shouldn't render twice, developpement or not.  
Just to clarify. What's executed twice in StrictMode when in dev environement are the `useEffect`'s callbacks. But it's not what we are talking about here.  

Infact the Login component render twice because the Template passed as prop is a lazy component that is downloaded on demand.  
This was not a good call on my side. The template is used in every pages so we can have a faster print and render only once by making it a hard import instead.  

I've just updated Keycloakify and the starter to implement this.  

Now the page component only render once.  

Thanks for the heads up!
