### ISSUE TITLE
index.ftl in account theme

### ISSUE THREAD

**Issue by sorooshjaberi** [keycloakify/keycloakify#485]
| keycloakify | ^7.15.8 |
|-------------|---------|
| keycloak    | 21.1.2  |

we are trying to build the account theme using keyclokify but the problem is after adding index.ftl page and building the theme the theme does not work and return 'Internal Server Error' 

the server error is:
![image](https://github.com/keycloakify/keycloakify/assets/93154421/e50a6898-ae13-4487-82f3-1d10a278269a)

according to my investigate the problem occur  when java want to fill **${url.resourcesPath}** but the variable is null or does not exists while other pages like **account.ftl** or **login.ftl** seems ok

index.ftl:
![image](https://github.com/keycloakify/keycloakify/assets/93154421/f46bcce7-e4ea-46cb-b5e4-cee81022767c)

what's the problem? don't i have access to ${url.resourcesPath} in index.ftl ?

**Comment by garronej** [comment]
Hello @sorooshjaberi,  

I don't understand specifically what's going wrong in your case but it's most certainly fixed in v9 of Keycloakfiy.  

Account themes genereated by Keycloakify prior to v9 are not compatible with Keycloak 23 and up.  
I think you will have to migrate to the newer version of keycloakify anyway or your theme will prevent you from upgrading your Keycloak version which is not good obviously.  

So I encougage you to implement the few steps described here https://docs.keycloakify.dev/migration-guides, update Keycloakify.  
If the problem persist come back here and I'll see what's up.

**Comment by arsicdejan** [comment]
@garronej We are trying to build a custom admin theme using Keycloakify v9, but Keycloak version we are using is 21.1.1 and we are facing the same issue. Do you think it is a compatibility issue?

**Comment by garronej** [comment]
Hello @arsicdejan,  

Unfortunately Admin theme are not supported by Keycloakify. It's not an imediate priority for us since only the Keycloak instance administrator see thoses pages.  
Are you sure your talking about Admin and not Accout?

**Comment by arsicdejan** [comment]
@garronej My bad, I misunderstood my colleague. Thank you and sorry for your time.
