### ISSUE TITLE
Can't find "kcInputGroup" classKey, "showPassword"  and "hidePassword" messageKey to implement the password visibility toggle from KC23

### ISSUE THREAD

**Issue by Moulyy** [keycloakify/keycloakify#493]
Hello, I updated the keycloakify version of my project to the latest version (9.1.8)

In the relase note of the 9.0.0 version,  It is written that the version supports version 23 of keycloak

Should I be able to find the messageKey "showPassword" and "hidePassword" in the keycloakify i18n types
as well as the classKey "kcInputGroup" that keycloak provides in version 23?

Thanks in advance, I may have missed something

**Comment by garronej** [comment]
I just updated Keycloakify. It now uses the messages from Keycloak 23.0.4.  

Thanks for the heads up!

**Comment by Moulyy** [comment]
Thanks for this update, what about the ClassKey type? Is it possible to add "kcInputGroup" in the type definition? and to ensure that we can retrieve "kcInputGroup" with the getClassName function of useGetClassName? Thank you for your quick responses.

**Comment by garronej** [comment]
Keycloakify essentially consists of two main components: the build tool and a library of React components, which is a direct translation of Keycloak's built-in default theme. The React component library serves primarily as a foundation, providing users with a base rather than starting from zero. It's simpler to incrementally modify an existing, functional setup than to develop a theme from scratch.

The point I'm making is that the library's offerings do not limit you. You have the freedom to implement any changes you desire, applying any classes as you see fit.

That said, if you wish to contribute by submitting a pull request for these two files—to add additional default classes that weren't included when I initially began porting the base theme to React—you are more than welcome:

https://github.com/keycloakify/keycloakify/blob/main/src/login/TemplateProps.ts
https://github.com/keycloakify/keycloakify/blob/main/src/login/lib/useGetClassName.ts

I will promptly merge and release a new version.

**Comment by Moulyy** [comment]
PR is created, Thank you very much !
https://github.com/keycloakify/keycloakify/pull/495
