### ISSUE TITLE
Unable to access kcContext.properties

### ISSUE THREAD

**Issue by huyenvu2101** [keycloakify/keycloakify#520]
Hi, I'm trying to migrate an existing `.ftl` theme to ReactJS and have encountered some issues.

I aim to make the logo and favicon URLs dynamic so that I can customize these images for each realm. In pursuit of this, I referred to [extraThemeProperties](https://docs.keycloakify.dev/build-options#extrathemeproperties) and decided to add the URL to the environment. I successfully added a new theme property. However, when attempting to access properties from the `kcContext`, I encountered the error "Property 'properties' does not exist on type 'KcContext'." Upon inspecting the `KcContext` from the console, I couldn't find the `properties` field.

**More Information:**
- Part of my `package.json` file:

```json
"version": "5.1.4",
"keycloakify": {
    "themeName": "myrealm-v3-react",
    "loginThemeResourcesFromKeycloakVersion": "19.0.1",
    "extraThemeProperties": [
        "locales=en,vi",
        "logoUrl": "${env.LOGO_URL}"
    ]
},
"dependencies": {
    "evt": "^2.5.7",
    "keycloakify": "^9.1.9",
    "node-fetch": "2.6.1",
    "react": "18.1.0",
    "react-dom": "18.1.0"
},
```
Thank you

**Comment by garronej** [comment]
Hello @huyenvu2101,  

A few things:  

- The type definition for the `KcContext["properties"]` has been added very recently, you should update Keycloakfy.  
- Regardless of what TypeScript says, the kcContext.properties does exist at runtime. The type definition of the KcContext is meerly a manually updated reflexion of what's actually observed to be there at runtime.  It's the Keycloak server that fills up the KcContext, not keycloakify. Keycloakify just convert the FTL context into a JavaScript context.  
- I see you're specifying your Keycloakify options in your package.json. I assumer you're using Webpack and not Vite? Because if you're using Vite, the keycloakify options are better defined in the `vite.config.ts`.  

See: https://docs.keycloakify.dev/environnement-variables  


![image](https://github.com/keycloakify/keycloakify/assets/6702424/6fc13720-45fb-4716-b49b-7d2f3f939d59)

**Comment by huyenvu2101** [comment]
thank you for your quick response, I'll try
