### ISSUE TITLE
using recaptchaRequired, recaptchaSiteKey variables in login.tsx

### ISSUE THREAD

**Issue by igrevkr** [keycloakify/keycloakify#523]
Hi, I'm AIden Kim from Korea.

We are customizing keycloakify for the login page now
But I'm faced with the login recaptcha variables.
I need to use recaptcha in the login page.

In the login.tsx, there is no way that I can get an access these two variables recaptchaRequired, recaptchaSiteKey.
I found that those variable types defined in the core KcContext( which is in node_modules/keycloakify/~~KcContext.
and those two variables exists only in Register model.
 
I temporarily solved this issue by using "declare let kcContext: any;" ( which means I use the gloabl variable in javascript) 
Otherwise storybook shows an error using declare.
But build-keycloak-theme and applying to the keycloak/theme are working well.

Please  let me know how to get through this.
Thank you in advance

**Comment by garronej** [comment]
Hello @igrevkr,  

I can add  `recaptchaRequired` and `recaptchaSiteKey` to the type declaration of the `KcContext` in the login page but are you sure that Keycloak actually provides thoses values.  

Could you do a `console.log(kcContext)` in your debugger to make sure:  

![image](https://github.com/keycloakify/keycloakify/assets/6702424/2445fdd7-f14e-4bb1-ae29-0ffb7740bb5a)

**Comment by igrevkr** [comment]
@garronej Thanks for the quick response.
I know I can use the KcContext variable and I used it already.
![image](https://github.com/keycloakify/keycloakify/assets/101522157/765bc82a-4e2d-476d-91e3-a02b4bef9d20)

But since KcContext.d.ts only use those variable(recapchRequired, recaptchaSiteKey), I can't use those two variables
![image](https://github.com/keycloakify/keycloakify/assets/101522157/3f361f17-90e8-4124-94a0-099d81488313)

like this
![image](https://github.com/keycloakify/keycloakify/assets/101522157/ea3693d7-5f1f-4ab8-a34f-1b7d26760bad)

error
![image](https://github.com/keycloakify/keycloakify/assets/101522157/265eb0d5-ed1e-46d2-8625-f6831ffda653)

**Comment by garronej** [comment]
I think you got things mixed up between the type definition and the runtime values.  

The type definitions are just here to help but they are *not* the source of truth.  
Using the global kcContext instead of making the kcContext flow into components isn't a great idea.  
If you need something that isn't on the KcContext type you can just do:  

```ts
(kcContext as any).recapchaRequired
```

If recapchaRequired isn't defined in the login page ( if `(kcContext as any).recapchaRequired` is always undefined) there's nothing Keycloakify can do about it.  
It's Keycloak that defines what available in pages.  

If you need futher support you can join our discord server: https://discord.gg/kYFZG7fQmn

**Comment by garronej** [comment]
It now works: https://storybook.keycloakify.dev/?path=/story/login-register-ftl--with-recaptcha
