### ISSUE TITLE
Accessing User Attributes in Keycloakify Forms

### ISSUE THREAD

**Issue by henry-azer** [keycloakify/keycloakify#539]
Hello @garronej,

I am currently seeking guidance on the integration of additional fields into both the registration or login update profile forms. Specifically, my objective is to incorporate new fields into these forms and subsequently store the corresponding values in user attributes. Could you kindly provide advice on the procedure for accessing user attributes within Keycloakify?

Thank you for your assistance and for developing this awesome tool!

Best regards,
Henry Azer

**Comment by garronej** [comment]
Hello @henry-azer,  

Unfortunately you're trying to build your theme in a transition period.  
I'm activeley working on uptading Keycloakify to reflect the changes made in Keycloak 24 and regarding user profiles there are a few.  

My advise is, for now, build a theme targeting Keycloak 23 and in a few day (hopfully) I will release an update guide to update Keycloak theme so that it's compatible with Keycloak 24.  

Here is the documentation regarding your question: https://docs.keycloakify.dev/realtime-input-validation

**Comment by garronej** [comment]
I need to create a video tutorial to help users navigate the Keycloak interface, specifically for creating custom fields and adding them to the JWT.

As of now, Keycloakify version 10.0.0-rc.136 is fully compatible with all Keycloak versions and offers a complete set of features. The documentation website is almost finished, but it’s missing a few sections, including a guide on configuring User Profile Attributes in Keycloak. While this falls slightly outside the scope of the Keycloakify project, I feel that without a detailed guide, users might struggle to figure things out on their own. This is especially important considering a known bug in the admin console:

[View the screen recording here.](https://filedn.com/lYPEPucNMheV19aDu23lK0Q/misc/Screen%20Recording%202024-08-17%20at%2012.18.24.mov)
