### ISSUE TITLE
Removing JS comments for productionized builds

### ISSUE THREAD

**Issue by gim-** [keycloakify/keycloakify#542]
Currently Keycloakify adds JS comments which look like this:
```js
/*If you need 'X' on PAGE, please submit an issue to the Keycloakify repo*/
```
I can understand the reasoning behind it, but this looks a bit out of place and doesn't add much value in production environments. This information is only relevant for developers during development/testing stage. Currently I haven't found an easy way to get rid of them. 

Sure they can be removed in the [post-build hook](https://docs.keycloakify.dev/build-options#postbuild-hook) script, something like:
```js
postBuild: async keycloakifyBuildOptions => {
  const fs = await import('fs/promises');
  const path = await import("path");

  const ftlTemplates = (await fs.readdir(keycloakifyBuildOptions.keycloakifyBuildDirPath, {recursive: true}))
    .filter(file => file.endsWith(".ftl"))
    .map(file => path.join(keycloakifyBuildOptions.keycloakifyBuildDirPath, file))

  for (const file of ftlTemplates) {
    let content = await fs.readFile(file, "utf8");
    content = content.replace(/<#local .*?\/\*If you need.*?\*\/"]>/g, "")
    await fs.writeFile(file, content, "utf8");
  }
}
```
But this is basically a hack, ideally these comments shouldn't be there in the first place.

Perhaps a build option could be added to suppress them for production builds?

Related part of the code:
https://github.com/keycloakify/keycloakify/blob/585c279d10e3080f8a9e4fb0361563fbaf3bace6/src/bin/keycloakify/generateFtl/ftl_object_to_js_code_declaring_an_object.ftl#L510

**Comment by garronej** [comment]
Hello @gim-,  

Ok I will add a new param in the next version to disable theses logs in the HTLM being sent down.  

I will make it opt in thoug because it does make my life much easyer for dealing with issues.  
I can just tell pepoles to copy past the HTML and figure what's going on.  

There will also be a way to explicitely filter the filelds that should be excluded from the kcContext on the backend side.  

I'm in the mist of a big update though so it might take some time before it land, I'd say maybe 2 weeks.

**Comment by garronej** [comment]
Done in Keycloakify v10!
