### ISSUE TITLE
how to hide kcContext object in console.log

### ISSUE THREAD

**Issue by MatheusHCP** [keycloakify/keycloakify#562]
I noticed that after the build and theme are selected in production, the data from kcContext is exposed in the console.log if someone tries to access it. Is there any way to obfuscate this object from being accessed in the console log easily? Minifying or obfuscating the code.

**Comment by garronej** [comment]
Hi @MatheusHCP 

obfuscating the kcContext object declaration code is technically challenging would probably degrade the performance of the FreeMarker templating. Since the code is dynamically generated by the Keycloak server for each request, it's not as simple as adding an extra build step.

Regarding detaching the Keycloak Context from the global scope, it's technically achievable. However, users can still access it via "view page source," making such an effort somewhat pointless.

It's important to note that the context provided by Keycloak during the FreeMarker templating only includes non-sensitive information. These are details intended for generating the html that will be send down to the client.

The only way in which the Keycloakify approach is different is that the the actual generation of the page structure is done client side instead of server side.  

You raise a pertinent point regarding the excess information sent to the client. Keycloakify currently does not filter the data, sending all available information to ensure robustness and maintainability. However, this approach isn't optimal. We aim to refine this process by selectively transmitting necessary data on a per-page basis in future updates, starting after Keycloakify version 10.

Best regards,

Related: https://github.com/keycloakify/keycloakify/issues/525

**Comment by MatheusHCP** [comment]
Thanks @garronej  for the explanation, I thought the data received was something confidential that would be a vulnerability.
