### ISSUE TITLE
How to add custom pages

### ISSUE THREAD

**Issue by patmoshosting** [keycloakify/keycloakify#564]
How do I create a custom page in Keycloakify? As far as I can tell, the only relevant line in the documentation is [here](https://docs.keycloakify.dev/limitations#i-do-it-only-for-my-project) where it says "Check out how my-extra-page-1.ftl and my-extra-page-2.ftl where added to [the starter project](https://github.com/keycloakify/keycloakify-starter/tree/main)", but in fact those pages were not added in the starter project; the TypeScript files for the pages exist, but the pages do not appear in the nav bar and do not have URLs in `kcContext`.

**Comment by garronej** [comment]
Hello @patmoshosting,  

The documentation is somewhat missleading.  
I souldn't have named this "extra pages". It's not possible to add extra steps to the authentication process just at the theme level.  
The extra page feature is for pepole who have a custom Keycloak extension, like for example the integration of a retina scanner or something like that, and this extention adds a user facing page to keycloak.  
This is a very advanced usecases that very few pepoles acutally uses it should not be incuded in the starter.  

What pepoles often actually want to do is to subdivide a form into multiple steps like googles does it for example or add a link to a page that give extra information.  
This would be done at the done at the React level since Keycloak does not need to be involved in that.   

If you're just starting your theme now, I sugest you wait a few days for Keycloakify 10 to be released.  
It will be much easyer.  

If you can't wait here is that starter for Keycloakify 10 but the documentation is not out yet: https://github.com/keycloakify/keycloakify-starter/tree/keycloakify_10
