### ISSUE TITLE
Password confirmation validation doesn't work properly on the Register page.

### ISSUE THREAD

**Issue by ayoam** [keycloakify/keycloakify#593]
Password matching validation only works when the password-confirm field is updated. It doesn't work when the password field is updated. 
In this case, the form is submittable, and I will receive a password mismatch error from the backend.

https://github.com/user-attachments/assets/363e5ee8-79b3-4756-915e-e84e39f8b780

**Comment by garronej** [comment]
Hello @ayoam,  

Good catch thanks for reporting.  

Side question, I see you've implemented client side password policy validation.  
Are you configuring the policies on the Keycloak server and using the passwordPolicies object:  
<img width="1189" alt="image" src="https://github.com/user-attachments/assets/bff31344-822c-41e3-a350-6d48d091a2a0">  

Or did you hard code thoses rules in your theme?

**Comment by ayoam** [comment]
Hi @garronej 

I configured the password policies on the Keycloak server admin dashboard .

I have a side question: I noticed that the Password regex policy is not included in the Password policies object. Will it be exposed in the future?

**Comment by garronej** [comment]
It's fixed in `10.0.0-rc.17` that have just been released.  

But I suggest you set `doMakeUserConfirmPassword` to `false`. It's a pain for the users to have to type a complex password twice. Making user confirm their password is a legacy practice.  
https://github.com/keycloakify/keycloakify-starter/blob/1604dee71c91f4d711bc93bcf77f0f04dfd7d57d/src/login/KcPage.tsx#L11  

> I have a side question: I noticed that the Password regex policy is not included in the Password policies object. Will it be exposed in the future?  

> I have a side question: I noticed that the Password regex policy is not included in the Password policies object. Will it be exposed in the future?  

Hum, intresting, this would be a feature request for https://github.com/jcputney/keycloak-theme-additional-info-extension, the library that Keycloakify uses uner the hood for this.

**Comment by ayoam** [comment]
Thank you @garronej for your prompt and detailed response!

**Comment by rob-long** [comment]
@garronej  PasswordPolicies not availabe on 'login-update-password.ftl'?
