### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by PietroFalcetti** [keycloakify/keycloakify#605]
Hello, 

I'm getting the following error when my app is redirected to the keycloak login page:
`
ERROR [org.keycloak.forms.login.freemarker.FreeMarkerLoginFormsProvider] (executor-thread-1) Failed to process template: org.keycloak.theme.FreeMarkerException: Failed to process template login.ftl`

It makes the app crash.

I'm on keycloak 24.0.3, using keycloakify ^9.3.1.

This is happening when i'm using my custom theme.
If I pick another theme from the keycloak admin console for my app (ex. the base keycloak theme, without keycloakify customization), the error is gone ...

Can anyone help ? 

Thank you in advance,

Pietro

**Comment by garronej** [comment]
Hello @PietroFalcetti,  

I'm very sorry you are experiencing this issue.  
It's due to the fact that you're still using Keycloakify 9.  
Despite the fact that keycloakify 10 is still il release candidate (because I didn't fully complete the documentation and the migration guide from v9 to v10) the v10 of keycloakify is the only one that supports the latest versions of Keycloak.  

v10 is production ready you can go ahead and implement it.  

Here is the starter for it:  

https://github.com/keycloakify/keycloakify-starter

And here is the documentation:  

https://docs.keycloakify.dev/   

If you have any aditional question you're welcome to join our discord server:  

https://discord.gg/kYFZG7fQmn
