### ISSUE TITLE
While Trying to add html in display name after i build my theme. The html is not rendered.

### ISSUE THREAD

**Issue by sgs-umar** [keycloakify/keycloakify#611]
![image](https://github.com/user-attachments/assets/402af49f-39e1-4e82-abfe-60b2e2a2f7b4)

I have inspected and noticed that the tags are not rendered but it works fine in other default themes

**Comment by garronej** [comment]
Hello @sgs-umar,  

Sorry about that and thanks for reporting. It's fixed in `keycloakify@10.0.0-rc.136`

**Comment by sgs-umar** [comment]
Hey @garronej is the v10 available yet?

**Comment by garronej** [comment]
@sgs-umar, yes, it’s been available for several weeks now. Version 10 is the only one fully compatible with the latest Keycloak release.

It’s still marked as release candidate because I want to complete the migration guide from v9 to v10 before making the official release.

**Comment by sgs-umar** [comment]
@garronej That's great, where can i find v10? I checked the branch, it was not there. Idk if i have looked properly, can you drop the link for v10? Thanks

**Comment by garronej** [comment]
v10 in on main. v10 is also pinned in the project project starter.** You can see it here: [keycloakify-starter package.json](https://github.com/keycloakify/keycloakify-starter/blob/144c45a7fd743f038c44f84d538ea4c1c9bb1ffd/package.json#L20).

To use this version in your project, simply include the following in your `package.json`:

```json
"dependencies": {
    "keycloakify": "10.0.0-rc.137"
}
```

Your questions are a bit surprising since all the current documentation refers to v10. Additionally, the screenshot you shared shows a background image that's featured in the v10 documentation.

When did you start creating your theme? Did you use the starter project or follow the integration instructions? If you followed the [Keycloakify integration instructions](https://docs.keycloakify.dev/keycloakify-in-my-codebase) or used the starter, you should already be on v10. I recommend checking your `package.json` to confirm.

**Comment by sgs-umar** [comment]
Cool then, checked just now. I was using 10.0.0-rc.132 . I cloned the tailwind demo project. I have just started using it and exploring keycloakify.

Thanks for the input man will keep that in mind.
