### ISSUE TITLE
Are there any examples of how to create a template for a plugin?

### ISSUE THREAD

**Issue by Tonypz** [keycloakify/keycloakify#614]
Are there any examples on how to customize the pages of a plugin like [keycloak-2fa-email-authenticator](https://github.com/mesutpiskin/keycloak-2fa-email-authenticator)?  

Answer: No there is not!

**Comment by garronej** [comment]
Hello @Tonypz,  

You can refer to this example that customize the [`otp-form.ftl.ftl`](https://github.com/p2-inc/keycloak-magic-link/blob/main/src/main/resources/theme-resources/templates/otp-form.ftl) page that is provided by the [keycloak-magic-link](https://github.com/p2-inc/keycloak-magic-link) extension.  

You can apply the same process for [keycloak-2fa-email-authenticator](https://github.com/mesutpiskin/keycloak-2fa-email-authenticator).  
In this case the page is [`email-code-form.ftl`](https://github.com/mesutpiskin/keycloak-2fa-email-authenticator/blob/main/src/main/resources/theme-resources/templates/email-code-form.ftl).  

Additionally, to be able to test your theme in a local keycloak container you can edit your `vite.config.ts` like so:  

```ts
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { keycloakify } from "keycloakify/vite-plugin";

// https://vitejs.dev/config/
export default defineConfig({
    plugins: [
        react(),
        keycloakify({
            accountThemeImplementation: "none",
            startKeycloakOptions: {
                dockerImage: "quay.io/keycloak/keycloak:22.0.1",
                extensionJars: [
                    "https://github.com/mesutpiskin/keycloak-2fa-email-authenticator/releases/download/v0.4/keycloak-2fa-email-authenticator-v0.4-KC21.1.0.jar"
                ]
            }
        })
    ]
});
```  

If you do that, when you will run the `npx keycloakify start-keycloak` the Keycloak Docker container that will be started will be a Keycloak version 22 with the [keycloak-2fa-email-authenticator](https://github.com/mesutpiskin/keycloak-2fa-email-authenticator) extension already loaded.  
This will enable you to test in real condition.  

PS: I've used Keycloak 22 because it's says in the readme of the extension that thit is the last version of Keycloak keycloak-2fa-email-authenticator have been tested with.

**Comment by Tonypz** [comment]
Thank you very much!

**Comment by Tonypz** [comment]
<img width="1043" alt="image" src="https://github.com/user-attachments/assets/a59a5d3c-3b09-47c8-841c-7036af4d2d56">


I did not get the email-code-form.ftl template. Does the following vite configuration determine its connection ?

   extensionJars: [
                    "https://github.com/mesutpiskin/keycloak-2fa-email-authenticator/releases/download/v0.4/keycloak-2fa-email-authenticator-v0.4-KC21.1.0.jar"
                ]

**Comment by garronej** [comment]
I'm very sorry, I forgot to include the link to the documentation in my response:  

https://docs.keycloakify.dev/styling-custom-extension-page

I edited my answer.

**Comment by Tonypz** [comment]
@garronej Thanks for the quick response!
