### ISSUE TITLE
Any reason for dangerouslySetInnerHTML?

### ISSUE THREAD

**Issue by uchar** [keycloakify/keycloakify#652]
While generating code using eject-page, I often encounter the use of `dangerouslySetInnerHTML`. However, as the [React documentation](https://legacy.reactjs.org/docs/dom-elements.html) warns:

> Setting HTML from code is risky because it can inadvertently expose users to cross-site scripting (XSS) attacks.

e.g one example in the code located in login page is :

```
<span
     id="input-error"
     className={kcClsx("kcInputErrorMessageClass")}
     aria-live="polite"
     dangerouslySetInnerHTML={{
    __html: messagesPerField.getFirstError("username", "password")
 }}
/>
```
And if I change it to 
```
 <span id="input-error" className={kcClsx("kcInputErrorMessageClass")} aria-live="polite">
        {messagesPerField.getFirstError("username", "password")}
</span>
```
I noticed no behaviour change , is there a reason to use `dangerouslySetInnerHTML` ?

**Comment by garronej** [comment]
Hello @uchar,

Yes, there's a reason for this. The translation messages are HTML strings. If you didn't notice a difference, it's likely because the string you tested didn’t contain any HTML tags.

But it you test with:

```ts
export const { useI18n, ofTypeI18n } = createUseI18n({
  en: {
    backToLogin: "⏪ Back to <strong>Login page</strong>",
  },
  fr: {
    backToLogin: "⏪ Retour à la <strong>page de Login</strong>",
  },
});
```  

you’ll notice that “Login page” will not be in bold but appearing as literal `<strong>page de Login</strong>`

The potential danger of rendering runtime-generated strings as HTML arises when the strings come from untrusted sources, such as user input. However, this is not the case here. The strings being rendered are either the default Keycloak translations or translations you’ve provided yourself.

One caveat is that arguments can be injected into these HTML messages, and those arguments could potentially come from user inputs. However Keycloakify’s i18n system [escapes any HTML tags in message arguments](https://github.com/keycloakify/keycloakify/blob/07e4f99f8010578197cdda04ede998ef4f990be8/src/login/i18n/i18n.tsx#L225), preventing any security risks.

**Comment by uchar** [comment]
Hi @garronej , Your approach is a good start, but I think escaping of the tag is not enough , we should explore a better way to sanitize strings, such as using [DOMPurify](https://github.com/cure53/DOMPurify). https://github.com/cure53/DOMPurify/blob/1e2cb9b72150e87409c776cb28c192f06dc2251e/src/purify.js#L1006 

 Alternatively, we might be able to avoid sanitization and dangerouslySetInnerHTML altogether by using [html-react-parser](https://www.npmjs.com/package/html-react-parser) .

**Comment by uchar** [comment]
@garronej Also I found out that in the code we always return a [div with dangerouslySetInnerHTML](https://github.com/keycloakify/keycloakify/blob/07e4f99f8010578197cdda04ede998ef4f990be8/src/login/i18n/useI18n.tsx#L16) 
So basically also writing it in the pages itself seems unecessary unless they dont use i18 ( which as far as I see most of them does and the rest which doesnt have the risk of xss)

**Comment by garronej** [comment]
> Your approach is a good start, but I think simply escaping tags (`<`, `>`) is not enough.

There are some valid concerns, which I’ll explain below, but my implementation of HTML tag escaping in message arguments is not one of them. It takes a very strict approach, completely preventing any HTML tags from being rendered in message arguments (e.g., `msg("messageKey", "An argument with some <strong>HTML</strong>")`). While this might not offer the best developer experience, it's safe.  

> We should explore a better way to sanitize strings, such as using [DOMPurify](https://github.com/cure53/DOMPurify).

Currently, Keycloakify is dependency-free, and I’d like to keep it that way. Including DOMPurify would mean shipping an extra 21KB of JavaScript with every page render. It's crucial to keep the page payload as minimal as possible.
> Alternatively, we might be able to avoid sanitization and `dangerouslySetInnerHTML` altogether by using [html-react-parser](https://www.npmjs.com/package/html-react-parser).

Again, this would add a 28KB dependency.

> I also noticed that we’re consistently returning a [div with `dangerouslySetInnerHTML`](https://github.com/keycloakify/keycloakify/blob/07e4f99f8010578197cdda04ede998ef4f990be8/src/login/i18n/useI18n.tsx#L16).  
> This seems redundant unless we aren’t using `i18n` (which most of the pages do), as those that don’t use it don’t face the risk of XSS.

The only instances where we use `dangerouslySetInnerHTML` are when we aren't using the `msg()` function:  
- When it's a message directly from the Keycloak context, as seen [here](https://github.com/keycloakify/keycloakify/blob/07e4f99f8010578197cdda04ede998ef4f990be8/src/login/pages/Error.tsx#L22) (this is arguably an issue that this isn't escaped since it is in the default theme)
- Or when we need to concatenate some localized strings, like [here](https://github.com/keycloakify/keycloakify/blob/07e4f99f8010578197cdda04ede998ef4f990be8/src/login/pages/Info.tsx#L31-L43).

It would be beneficial to have an equivalent of Keycloak's `kcSanitize` function in JavaScript. In the default Keycloak theme, [this message is sanitized](https://github.com/keycloak/keycloak/blob/8ce8a4ba089eef25a0e01f58e09890399477b9ef/themes/src/main/resources/theme/base/login/template.ftl#L139-L140), but in Keycloakify, it is not, as you can see [here](https://github.com/keycloakify/keycloakify/blob/07e4f99f8010578197cdda04ede998ef4f990be8/src/login/Template.tsx#L154-L156).

You can find the implementation of the `kcSanitize` method [here](https://github.com/keycloak/keycloak/blob/8ce8a4ba089eef25a0e01f58e09890399477b9ef/services/src/main/java/org/keycloak/theme/KeycloakSanitizerMethod.java#L33).

If you're interested in submitting a PR to implement this function in `src/tools/kcSanitize.ts`, along with unit tests in [this directory](https://github.com/keycloakify/keycloakify/tree/main/test), I'd be happy to integrate it. Implementing this would also allow HTML in message arguments, as seen [here](https://github.com/keycloak/keycloak/blob/8ce8a4ba089eef25a0e01f58e09890399477b9ef/themes/src/main/resources/theme/base/login/template.ftl#L58-L59), which isn't currently the case since we take a more radical aproach by escaping any html tags in messages arguments.

**Comment by uchar** [comment]
@garronej the thing is XSS is not only about injecting react tags . In theory one can also add events like `onerror`  or `onclick` , or maybe special characters like  `"` `'` . overall doing it properly is a complex task I think adding 21kb worth it because those guys have a lot of experience in this field ( atleast untill keycloak itself add this as you said ) .
About the PR , Ok  I will take a look on it  and see what I can do

**Comment by garronej** [comment]
Great thank you.  
If we implement this function we can have exact parity with the default Keycloak theme regarding protection against XSS attacks

**Comment by garronej** [comment]
In v11.  

https://docs.keycloakify.dev/faq-and-help/migration-guides/v10-greater-than-v11#kcsanitize  


![image](https://github.com/user-attachments/assets/58ac3772-332d-4f31-b8c7-86c54446af51)  

Thank you for your help on that.
