### ISSUE TITLE
Remove patternfly from jar output

### ISSUE THREAD

**Issue by uchar** [keycloakify/keycloakify#662]
Is there a way to remove all styles from keycloakify and get pure html output from eject or build command  ? ( I want to use material ui I dont need any extra css library)
e.g just having `<p id="instruction1">` instead of `<p id="instruction1" className="instruction">`

Also even if I remove all className manually there is still reference of patternfly in stylesheet header and will downloaded upon page load , anyway to remove it completely from some of the pages that I dont use it ? e.g somehow override the header ?

![image](https://github.com/user-attachments/assets/2b07c779-7a52-4140-8cda-cb0d9ec14840)

**Comment by garronej** [comment]
Hello @uchar,  
Yes! It's possible and even recommended!  
https://docs.keycloakify.dev/customization-strategies/css-level-customization/removing-the-default-styles#removing-all-the-default-styles-at-once

**Comment by garronej** [comment]
PS: Since you have ejected all the pages, I wanted to let you know that I have recently abstracted away some logc from Template.tsx LoginPasskeysConditionalAuthenticate.tsx and LoginRecoveryAuthnCodeConfig.tsx.  

There is now a custom hook for the non template related logic of the components:  

You should apply this change, example with the template.tsx

![image](https://github.com/user-attachments/assets/20f5e647-0a9b-4185-997d-57e1a8f80cd0)

**Comment by uchar** [comment]
@garronej nice , thanks . this is exactly what I need , didnt see that page in document

**Comment by garronej** [comment]
I talk about it in the tutorial but it's after like 20 min of yapping so I do not blame you for missing it.  

I added a note for making it easyer to find:  
<img width="1189" alt="image" src="https://github.com/user-attachments/assets/a2bf56a5-6a09-43ff-bd4c-c8d851a79f57">

**Comment by uchar** [comment]
@garronej Yes its more understandable now , we can also have an option to eject pages with all styles disabled , what do you think? Sth like `eject-page --styling disabled `
