### ISSUE TITLE
Clarify that keycloak 26 is part of "all-other-versions.jar" and not "22-25"

### ISSUE THREAD

**Issue by corneliusroemer** [keycloakify/keycloakify#731]
I first thought keycloak 26 should use the `keycloak-theme-for-kc-22-to-25.jar`, wrongly assuming you had just not yet updated this.

However, looking at the PR, it's intentional that the range is 22-25. It seems 26 is part of `keycloak-theme-for-kc-all-other-versions.jar`.

This is slightly surprising (one wouldn't assume that just a range from 22-25 doesn't support a feature but below and above it would (or the inverse) but that seems to be the case?

I think one sentence about this in https://docs.keycloakify.dev/targeting-specific-keycloak-versions clarifying this would be fantastic!

Also, just out of curiosity, what's the reason 22-25 are special? What makes 26 more like 21 than 22?

**Comment by garronej** [comment]
Hello @corneliusroemer,  

I mention it in the video but you are right, it should be explicitely stated.  
I added a notice:  

<img width="942" alt="image" src="https://github.com/user-attachments/assets/06794e72-03cb-4d4d-a790-b2a99834f6c6">

> Also, just out of curiosity, what's the reason 22-25 are special? What makes 26 more like 21 than 22?  

We made a PR to Keycloak that have been merged and released with Keycloak 26.  
So now, we don't need to bundle any custom java code for having realtime password validation.  
Version older than 22 didn't had realtime password validation because we didn't bother adapting our java code for these older version.  
If that makes sense.

**Comment by corneliusroemer** [comment]
Perfect, thanks! Your work on keycloakify is so much appreciated!

I wish I had time to watch the videos, they are great but don't work super well with Google/site search for quick questions like this.

Amazing that you upstreamed the work. That explains why 22-25 is different, good job!
