### ISSUE TITLE
`start-keycloak` command does not run the docker container

### ISSUE THREAD

**Issue by dshtefan** [keycloakify/keycloakify#744]
Hello, I am facing a problem with docker container startup when running `keycloakify start-keycloak`. 
if the `keycloakify` version is `>11.4.0`, `docker run` command is not called. `npx vite dev` blocks the execution of further cli commands:

![image](https://github.com/user-attachments/assets/8b103afa-1d04-4517-8132-b42c60374f62)

**Comment by garronej** [comment]
Hello @dshtefan,  

Try running `npx vite dev` see what's hapenning.  

Otherwise, please provide more infos

**Comment by dshtefan** [comment]
Here is what I was able to find out during the debugging process:

The **startViteDevServer** command waited indefinitely for a port number because the UTF-8 source string contained ANSI color codes. Docker could not start because the port could not be parsed.

The solution to the problem was to add a function to remove the ANSI color codes before the match function.


**startViteDevServer.ts**
```typescript
const match = data
    .toString("utf8")
    .replace(/\x1b[[0-9;]*m/g, '') //Adding this line solves the problem
    .match(/Local:\s*http:\/\/(?:localhost|127\.0\.0\.1):(\d+)\//);

``` 
Source file:
https://github.com/keycloakify/keycloakify/blob/a66a37325676ae2ebfb4ba27d2eb506c6518a2a3/src/bin/start-keycloak/startViteDevServer.ts#L45-L47

**Comment by garronej** [comment]
Hello @dshtefan,  

Thank you for investigating.  
I've released the patch you suggested.  

However I don't understand why you're getting colors in that context.  
What environement are you on? You're the first to report having this issue.

**Comment by dshtefan** [comment]
@garronej Actually, nothing specific. I run this command inside the powershell console in vscode. The project is a monorepository using pnpm as package manager.

OS: windows 11
Node: v22.2.0

**Comment by garronej** [comment]
Ah ok I see. The bug only happens on Windows/powershell when you have a single page account theme and only with Keycloakify 11.4 that was released last week.  
This explains why it hasn't be reported earlyer.  

I'm unable to test the build command on windows because I can't do Docker in Docker on the cloud and I don't have a windows laptop.  

I guess the best solution would be to find the specific var env that keycloakify would need to set to disable colors for child process.  
However I'll leave it as is since your fix does the trick for this specifc issue.  

Thank you very much for investigating.
